name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@latest
    
    - name: Run actionlint
      run: actionlint